# Don't forget to activate Github pages for the repository.
# - Go to https://github.com/<user>/<repo>/settings/pages
# - For Build and Deployment -> Source, choose "Github Actions".

name: Deploy Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Graphviz
      uses: ts-graphviz/setup-graphviz@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt install libcairo2-dev pkg-config python3-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx-rtd-theme sphinx-automodapi

    - name: Build documentation
      run: |
        make docs
        touch docs/_build/html/.nojekyll

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with: 
        path: docs/_build/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

